# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build full solution with MSBuild
      run: msbuild /p:Configuration=Release /p:Platform=x64
    - name: Pack release archives
      run: |
        mkdir release
        Compress-Archive -Path .\ZoneFbx.GUI\bin\x64\GithubRelease\net9.0-windows\* -DestinationPath .\release\ZoneFbx.GUI_${{ github.ref_name }}.zip -Force
    # - name: Create Release
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     name: ZoneFbx.GUI ${{ github.ref_name }}
    #     files: release/**
    #     generate_release_notes: true
